In [27]:
from tf_utilities import turn_strings_into_vectors
import tensorflow as tf
import pandas as pd
import numpy as np

from neural import run
from preprocess import preprocess_accident_data

In [7]:
accidents = pd.read_csv('../.data/accidents_2005_to_2007.csv')

/home/private/anaconda3/envs/562/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [88]:
data = accidents[['Accident_Severity', 'Number_of_Vehicles', 'Day_of_Week', 'Speed_limit']]

In [40]:
accident_severity_names, accident_severity_vectors = turn_strings_into_vectors(data['Accident_Severity'])

In [69]:
accident_severity_name_2_index = {}
for i, name in enumerate(accident_severity_names):
    accident_severity_name_2_index[name] = i
accident_severity_name_2_index

{1: 0, 2: 1, 3: 2}

In [41]:
day_of_week_names, day_of_week_vectors = turn_strings_into_vectors(data['Day_of_Week'])

In [70]:
day_of_week_name_2_index = {}
for i, name in enumerate(day_of_week_names):
    day_of_week_name_2_index[name] = i
day_of_week_name_2_index

{1: 0, 2: 1, 3: 2, 4: 3, 5: 4, 6: 5, 7: 6}

In [53]:
values = data.values.copy()

In [80]:
accident_severity_matrix = np.zeros((len(data['Accident_Severity']), len(accident_severity_names)))

for i in range(len(data['Accident_Severity'])):
    accident_severity_matrix[i] = accident_severity_vectors[accident_severity_name_2_index[data['Accident_Severity'][i]]]
    
accident_severity_matrix, accident_severity_matrix.shape

(array([[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        ...,
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.]]), (570011, 3))

In [81]:
day_of_week_matrix = np.zeros((len(data['Day_of_Week']), len(day_of_week_names)))

for i in range(len(data['Day_of_Week'])):
    day_of_week_matrix[i] = day_of_week_vectors[day_of_week_name_2_index[data['Day_of_Week'][i]]]
day_of_week_matrix, day_of_week_matrix.shape

(array([[0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.]]), (570011, 7))

In [89]:
processed_data = np.column_stack((day_of_week_matrix, data['Speed_limit'].values.copy()))

In [91]:
processed_labels = np.column_stack((accident_severity_matrix, data['Number_of_Vehicles'].values.copy()))

In [105]:
processed_data.shape, processed_labels.shape

((570011, 8), (570011, 4))

In [118]:
amount = 100000
training_data, training_labels = processed_data[:amount], processed_labels[:amount]
test_data, test_labels = processed_data[amount:2*amount], processed_labels[amount:2*amount]

In [148]:
model, test_loss, test_accuracy = run_nn(
    training_data=training_data.astype(np.float32),
    training_labels=training_labels.astype(np.float32),
    test_data=test_data.astype(np.float32),
    test_labels=test_labels.astype(np.float32), epochs=100)

8 4
Epoch 1/100
10000/10000 [==============================] - 1s 125us/step - loss: 0.1743 - acc: 0.6771
Epoch 2/100
10000/10000 [==============================] - 0s 49us/step - loss: 0.1565 - acc: 0.6793
Epoch 3/100
10000/10000 [==============================] - 0s 46us/step - loss: 0.1523 - acc: 0.6793
Epoch 4/100
10000/10000 [==============================] - 0s 42us/step - loss: 0.1494 - acc: 0.6793
Epoch 5/100
10000/10000 [==============================] - 0s 47us/step - loss: 0.1491 - acc: 0.6793
Epoch 6/100
10000/10000 [==============================] - 1s 50us/step - loss: 0.1483 - acc: 0.6793
Epoch 7/100
10000/10000 [==============================] - 1s 50us/step - loss: 0.1472 - acc: 0.6793
Epoch 8/100
10000/10000 [==============================] - 0s 47us/step - loss: 0.1465 - acc: 0.6793
Epoch 9/100
10000/10000 [==============================] - 0s 46us/step - loss: 0.1465 - acc: 0.6793
Epoch 10/100
10000/10000 [==============================] - 0s 48us/step - loss: 0.146

10000/10000 [==============================] - 0s 43us/step - loss: 0.1446 - acc: 0.6793
Epoch 82/100
10000/10000 [==============================] - 0s 44us/step - loss: 0.1445 - acc: 0.6793
Epoch 83/100
10000/10000 [==============================] - 0s 43us/step - loss: 0.1446 - acc: 0.6793
Epoch 84/100
10000/10000 [==============================] - 1s 59us/step - loss: 0.1447 - acc: 0.6793
Epoch 85/100
10000/10000 [==============================] - 1s 53us/step - loss: 0.1446 - acc: 0.6793
Epoch 86/100
10000/10000 [==============================] - 1s 51us/step - loss: 0.1446 - acc: 0.6793
Epoch 87/100
10000/10000 [==============================] - 0s 45us/step - loss: 0.1446 - acc: 0.6793
Epoch 88/100
10000/10000 [==============================] - 0s 48us/step - loss: 0.1446 - acc: 0.6793
Epoch 89/100
10000/10000 [==============================] - 1s 51us/step - loss: 0.1446 - acc: 0.6793
Epoch 90/100
10000/10000 [==============================] - 0s 48us/step - loss: 0.1445 - acc: 

In [149]:
predictions = run_nn(
    training_data=training_data.astype(np.float32),
    training_labels=training_labels.astype(np.float32),
    test_data=test_data.astype(np.float32),
    test_labels=test_labels.astype(np.float32), prediction_set=processed_data[-1:], epochs=0)

8 4
10000/10000 [==============================] - 1s 111us/step


In [150]:
predictions

array([[2.2293    , 2.7296057 , 0.03645724, 2.422695  ]], dtype=float32)

In [151]:
processed_labels[-1]

array([0., 1., 0., 2.])

In [152]:
test_loss, test_accuracy

(0.18415261824131013, 0.6973)

In [95]:
accident_severity_matrix.dtype

dtype('float64')

In [147]:
import tensorflow as tf
from tensorflow import keras


def run_nn(training_data, training_labels, test_data, test_labels, prediction_set=None, epochs=10):

    input_count = training_data.shape[1]
    output_count = training_labels.shape[1]
    print(input_count, output_count)

    with tf.Session() as session:
        model = keras.Sequential([
            keras.layers.Dense(input_count),
            keras.layers.Dense(256, activation=tf.nn.relu),
            keras.layers.Dense(128, activation=tf.nn.relu),
            keras.layers.Dense(64, activation=tf.nn.relu),
            keras.layers.Dense(output_count, activation=None)
        ])

        model.compile(
            optimizer=tf.train.AdamOptimizer(), loss='mean_squared_error', metrics=['accuracy'])

        model.fit(training_data, training_labels, epochs=epochs)

        test_loss, test_accuracy = model.evaluate(test_data, test_labels)
        
        if prediction_set is not None:
            return model.predict(prediction_set)
            

        return model, test_loss, test_accuracy